---
title: "feitosa_leonardo_task_1"
author: "Leonardo Feitosa"
date: "01/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(naniar)
library(NbClust)
library(cluster)
library(factoextra)
library(dendextend)
library(ggdendro)
```


```{r}
## Read in the data
lter_data <- read_csv(here("data", "sbc_lter_registered_stream_chemistry.csv"))
```

```{r}
# Data wrangling
lter_tidy <- lter_data %>% 
  na_if(-999) %>% 
  mutate(timestamp_local = as.Date(timestamp_local))

# Calculating means by site
lter_group <- lter_tidy %>% 
  group_by(site_code) %>% 
  summarise(mean_nh4 = mean(nh4_uM, na.rm = T),
            mean_no3 = mean(no3_uM, na.rm = T),
            mean_po4 = mean(po4_uM, na.rm = T),
            mean_tdn = mean(tdn_uM, na.rm = T),
            mean_tdp = mean(tdp_uM, na.rm = T),
            mean_tpc = mean(tpc_uM, na.rm = T),
            mean_tpn = mean(tpn_uM, na.rm = T),
            mean_tpp = mean(tpp_uM, na.rm = T),
            mean_tss = mean(tss_mgperLiter, na.rm = T),
            mean_spec = mean(spec_cond_uSpercm, na.rm = T)) %>% 
  drop_na()

# Scaled numeric variables
lter_scaled <- lter_group %>% 
  select(2:10) %>% 
  scale()

# Update with site names
rownames(lter_scaled) <- lter_group$site_code
```

```{r}
# Calculating euclidian distances
lter_dist <- dist(lter_scaled, method = "euclidian")

# Hierarchical clustering
lter_hclust <- hclust(lter_dist, method = "complete")

plot(lter_hclust)
```

```{r}
# Plotting dendrogram
ggdendrogram(lter_hclust,
             rotate = T,
             size = 1.2) +
  labs(x = "Sites",
       y = "") +
  theme_bw() +
  theme(axis.title = element_text(size = 12, face = "bold", color = "black", hjust = 0.5),
        axis.text = element_text(size = 10, color = "black"),
        panel.grid = element_blank())

```


















