---
title: "feitosa_leonardo_a4_task2"
author: "Leonardo Feitosa"
date: "01/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(broom)
library(nlstools)
library(fishualize)
```

```{r}
# Read in the data
fish_catch <- read_csv(here("data", "fish_catch.csv"), skip = 2) %>% 
  drop_na() %>% 
  clean_names() %>% 
  mutate(wild_catch = as.numeric(wild_catch),
         year = as.numeric(year))

fish_final <- fish_catch %>% 
  mutate(year_new = 0:(n() - 1))
```

```{r}
# Exploratory data viz
ggplot(data = fish_catch, aes(x = year, y = wild_catch)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1950, 2012, by = 10)) +
  scale_y_continuous(breaks = seq(0, 100, by = 20))
```

```{r}
# Log transformed data
ggplot(data = fish_catch, aes(x = year, y = log(wild_catch))) +
  geom_point() +
  scale_x_continuous(breaks = seq(1950, 2012, by = 10))
```


Wild catches seem to follow a steady increase over the first five decades comprising the data and then reaching a plateau between the 1990s and 2010s. 

*INCLUDE EQUATION*

```{r}
# Create subset for the growth portion of the dataset
fish_exp <- fish_final %>% 
  filter(year <= 1990) %>% 
  mutate(log_wild = log(wild_catch))

# Get the estimate for slope
lm_fish <- lm(log_wild ~ year_new, data = fish_exp)
lm_fish
```

$K$ = 90
$A$ = 4.23
Based on the result above, **k** = 0.03.

```{r}
# Non-linear least squares
fish_nls <- nls(wild_catch ~ K/(1 + A*exp(-k*year_new)),
                data = fish_final,
                start = list(K = 90, A = 4.23, k = 0.03),
                trace = TRUE
                )
```

```{r}
summary(fish_nls)

# Model outputs
model_out <- broom::tidy(fish_nls)
```


```{r}
fish_predict <- predict(fish_nls)

# Bind predictions and original df
fish_complete <- data.frame(fish_final, fish_predict)


# Plot them
ggplot(data = fish_complete, aes(x = year_new, y = wild_catch)) +
  geom_point(color = "cyan4") +
  geom_line(aes(x = year_new, y = fish_predict),
            color = "darkred",
            size = 1) +
  labs(x = "Number of years",
       y = "Number of wild fish caught") +
  theme_bw() +
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 11, color = "black", face = "bold", vjust = 0.7))
```










